$pdf_previewer = 'zathura';
$pdflatex = 'pdflatex --shell-escape --interaction=nonstopmode --synctex=1 %O %S';
$clean_ext = "aux fdb_latexmk fls  log nav snm";
$lualatex = 'lualatex --shell-escape --interaction=nonstopmode --synctex=1 %O %S';
